// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1aje3ZliqAdYo0Aw3srudnvHMgnOxWY',
    appId: '1:710926427099:web:7ed2e414c7c83878f1bdfe',
    messagingSenderId: '710926427099',
    projectId: 'to-do-app-flutter-25d71',
    authDomain: 'to-do-app-flutter-25d71.firebaseapp.com',
    storageBucket: 'to-do-app-flutter-25d71.appspot.com',
    measurementId: 'G-DB2W918JN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHaj6qfudnxSQC0WquvGHVJxm7q68gfk',
    appId: '1:710926427099:android:4607c4a8bc4f74bbf1bdfe',
    messagingSenderId: '710926427099',
    projectId: 'to-do-app-flutter-25d71',
    storageBucket: 'to-do-app-flutter-25d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBe4Aps0WAuCPirq9HvLg5r0HsED4dMo',
    appId: '1:710926427099:ios:ff38fe5256fdd23bf1bdfe',
    messagingSenderId: '710926427099',
    projectId: 'to-do-app-flutter-25d71',
    storageBucket: 'to-do-app-flutter-25d71.appspot.com',
    iosClientId: '710926427099-7m73it0ln9p4sfgmeq56c96tir5anhsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBe4Aps0WAuCPirq9HvLg5r0HsED4dMo',
    appId: '1:710926427099:ios:733953fa6bbb0940f1bdfe',
    messagingSenderId: '710926427099',
    projectId: 'to-do-app-flutter-25d71',
    storageBucket: 'to-do-app-flutter-25d71.appspot.com',
    iosClientId: '710926427099-2ioqd6d4tnvkt0u23qhq2k2h8ukh6h95.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
